// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ignazlwztvyvjflonepg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnbmF6bHd6dHZ5dmpmbG9uZXBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4Nzg3MDEsImV4cCI6MjA2MjQ1NDcwMX0.umdslz5oFI__ypLa9fT0SVl5oZj4Nf8cpJ0y3G6b2WA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);